modified the .eslintrc file and and eslint rules to ES6 2020
elit-altum/AuthExp-Express-Starter pull request #5
Opened 2020-09-19 16:13 UTC by raj5036

Updated the codebase as pre issue #2 .Please check it .

2020-09-19 16:39 UTC, elit-altum requested changes

2020-09-19 16:39 UTC, elit-altum commented on .eslintrc
> +        "jsx": true
Any reasons for this? JSX is preferred for react only I believe. We want to keep this module as flexible and un-opinionated as possible.

2020-09-19 16:40 UTC, elit-altum commented
@raj5036 Do you want this PR to specifically count for Hacktoberfest? If that's the case, I'd merge it on 1st October only.

2020-09-20 05:22 UTC, raj5036 commented
OK @elit-altum  I am making the change. I added the jsx option mistakenly , but ok I will remove it.

And yes I want this PR to count for Hacktoberfest. So please merge it on 1st October .

2020-10-02 05:58 UTC, Max19thl commented
I am making the change. I added the jsx option mistakenly , but ok I will remove it. yes I want this PR to count for Hacktoberfest. So please merge it on 1st October .

2020-10-03 08:14 UTC, elit-altum commented
@raj5036 Please resolve conflicts

2020-10-03 13:45 UTC, raj5036 commented
Is it Okay now ?

2020-10-03 16:24 UTC, raj5036 commented
@elit-altum Is it Okay now? Or should I delete this PR and a  create a new one?

2020-10-04 17:11 UTC, merged